### ISSUE TITLE
CI: Checkout JS Error Duplicate HTML Element ID's

### ISSUE THREAD

**Issue by jkergosi** [HotcakesCommerce/hotcakes-commerce-core#144]
## Describe the bug
I found a js error: on the checkout page (v 3.2.0):

Found 3 elements with non-unique id #loginChoose:

<input checked=​"checked" id=​"loginChoose" name=​"loginChoose" type=​"radio" value=​"#hcTabNewAccount" style=​"position:​ absolute;​ z-index:​ -1;​ opacity:​ 0;​">​ 
<input id=​"loginChoose" name=​"loginChoose" type=​"radio" value=​"#hcTabLogin" style=​"position:​ absolute;​ z-index:​ -1;​ opacity:​ 0;​">​ 
<input id=​"loginChoose" name=​"loginChoose" type=​"radio" value=​"#hcTabGuest" style=​"position:​ absolute;​ z-index:​ -1;​ opacity:​ 0;​">​

According to Reto, This is a DOM error and is affecting checkout only if you have Google Ecommerce Tracking activated. As a work around if you can disable Tracking and checkout works.

## Software Versions
- DNN:  09.02.00
- Hotcakes:  03.02.00

## To Reproduce
1. Go to Checkout Page
2. View Console
3. BAM! See error

## Expected behavior
No JS errors

## Error log
NA

**Comment by hismightiness** [comment]
Related to community forum post:  https://hotcakes.org/Forums/g/posts/m/911/Checkout-Page-JS-error

Thanks for posting this!  :)

**Comment by hismightiness** [comment]
Resolved in PR #261
