### ISSUE TITLE
CI: Default Sort for Category Viewer

### ISSUE THREAD

**Issue by jkergosi** [HotcakesCommerce/hotcakes-commerce-core#145]
## Is your feature request related to a problem?
If 1 sort is selected, it still prompts the user to select it.

## Describe the solution you'd like
If 1 sort is selected, enable it by default and hide the sort dropdown for the user.
Ex. If I deselected all sorts except SKUs, hide the sort dropdown  and automatically sort it by SKUs.

**Comment by hismightiness** [comment]
Great suggestion!  Thanks, Jason.

For everyone, please know that this is also being discussed in the Hotcakes forums: 

https://hotcakes.org/Forums/g/posts/m/916/Default-Sort-for-Hotcakes-Category-Viewer

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
