### ISSUE TITLE
CI: Second Portal Hotcakes Wizard May Fail

### ISSUE THREAD

**Issue by WillStrohl** [HotcakesCommerce/hotcakes-commerce-core#161]
## Describe the bug
Creating a second instance of Hotcakes on a second website in the same DNN instance of DNN may cause the wizard and/or images to fail.

## Software Versions
- DNN:  ???
- Hotcakes:  03.02.00

## To Reproduce
1. Install DNN and then Hotcakes Commerce
2. Create two top-level (parent) portals.
3. Configure Hotcakes on one of the portals using the configuration wizard.
4. Navigate to the second portal, then configure Hotcakes there.

## Expected behavior
The wizard set-up experience is identical in both portals.  Store pages are created.  Admin page(s) is/are created.  Images are not broken.

## Actual behavior
The first wizard completes as expected, without error.  New store pages are created and images are load correctly.  The second website has errors occur on the first step of the wizard causing it to "hang," and the images are broken.

## Additional context
Community Forums Thread:  https://hotcakes.org/Forums/g/posts/m/1020/Hotcakes-and-Child-Portals

**Comment by hismightiness** [comment]
Issue #152 should be resolved as part of or before this issue.

**Comment by WillStrohl** [comment]
No longer an issue. Resolved in a prior release.
