### ISSUE TITLE
ModuleID var in JS and dnn9 

### ISSUE THREAD

**Issue by moslem7026** [HotcakesCommerce/hotcakes-commerce-core#169]
## Describe the bug
DNN 9 and above, personabar uses JS and some variable in js is defined to load personabar Correctly like `moduleid`

## Software Versions
- DNN:  09.00.00
- Hotcakes:  03.02.00

## To Reproduce
1. add hotcake category viewer to the page
2. set drill down as view 
3. persona bar does not load correctly because of var conflict
4. `DesktopModules\Hotcakes\Core\Scripts\hcc.views`  

change `moduleid` to `moduleidjs` may solve the problem
 var moduleid  = form.data("moduleid");

**Comment by hismightiness** [comment]
Excellent find!  Would you mind providing a screenshot showing the error message?

**Comment by moslem7026** [comment]
![tempsnip](https://user-images.githubusercontent.com/5102754/46651256-5541f700-cbac-11e8-8600-62b406395cc1.png)
as you can see , perosnabar not loaded and console error occured

**Comment by hismightiness** [comment]
During initial testing, this appears to break the ability for DNN 9.xx to display the actions menus.

**Comment by hismightiness** [comment]
Hmmm... This may have either been a caching or upgrade issue.

**Comment by hismightiness** [comment]
This has been confirmed to resolve the issue in a clean installation.
