### ISSUE TITLE
SI: Checkout order workflow MembershipTask fails w/ bundled products

### ISSUE THREAD

**Issue by sniravj** [HotcakesCommerce/hotcakes-commerce-core#175]
## Describe the bug
1. You can create bundle product which can contain only single product
2. For such products in Hotcakes.Commerce.Dnn.Workflow.MembershipTask.Execute code fails to load relative BunduleProduct object resulting error in ProcessSingleProduct function and eventually results in checkout failure with unknown exception

## Software Versions
- Hotcakes:  03.02.00
- Hotcakes:  03.02.01

**Comment by hismightiness** [comment]
It may also occur in other areas, but specifically for this instance, it was discovered that products in the MemberShip task with bundled products had their respective product ID (bvin) and bundled product ID (bvin) loaded into their respective class properties, but the BundledProduct property is NULL.  This is most likely an issue somewhere in the repository logic (e.g., LoadSubItems).

**Comment by hismightiness** [comment]
Verified to be resolved in the pending 03.02.02 release.  But there isn't a PR or commit associated with this Issue.  Did I push it in another bundled commit or is it related to a specific version of DNN?  🤔
