### ISSUE TITLE
SI: When Deactivating a Product It Still Shows Under Related Products

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/hotcakes-commerce-core#211]
## Describe the bug
When a product is set as inactive but is referenced as a related product it will still show on the site. For example if I have two products 1234 and 7890 and 7890 is a related product to 1234 but 7890 is deactivated the related products section will show 7890 as a product that you can access. When you click you get a message saying the product is no longer available for sale. Inactive products will not show.

## Software Versions
- DNN:  9.2.2
- Hotcakes:  3.2.0

## To Reproduce
1. Go to Product Management
2. Add a related product
3. Go to the related product and deactivate it
4. Navigate to the store and select the product that contains the related product
5. See the related products section shows the deactivated product

## Expected behavior
When a product is set to inactive it should not be visible on the site in related products.

## Actual behavior
The product is shown and is clickable but you receive a message saying the product is not available.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
