### ISSUE TITLE
Role Expiration Date is Ignored in Sales Promotion

### ISSUE THREAD

**Issue by parasdaryanani** [HotcakesCommerce/hotcakes-commerce-core#214]
## Describe the bug
Sales based on membership roles ignore the role expiry date, i.e. if a user has an expired membership, they still get promotions based on the role.

## Software Versions
- DNN:  08.03.00
- Hotcakes:  03.02.01

## To Reproduce
1. Create a new user X
2. Create 2 roles: 'pro' and 'premier'.
3. Assign pro membership to X with expiry date 01/01/2020.
3. Assign premier membership to X with expiry date 01/01/2015.
4. Create a storewide sale for 'pro' role = 5% discount.
5. Create a storewide sale for 'premier' role = 10% discount.
6. Create a dummy product with price $100.
7. Login as X and add the dummy product to cart.

## Expected behavior
Since X's premier membership is expired, the sale should not apply and the cart price should be $100 - 5% = $95.

## Actual behavior
Both premier and pro membership are taken into account and price in cart is $100 - 5% - 10% = $85.

## Additional context

Expiry date is not taken into account when applying promotions, as seen in `Hotcakes.Commerce.Dnn\Marketing\Qualifications\UserIsInRole.cs`

```c#
private List<RoleInfo> GetCustomerRoles(CustomerAccount customer)
        {
            var user = DnnUserController.Instance.GetUser(_portalId, Convert.ToInt32(customer.Bvin));
            var roles = RoleController.Instance.GetUserRoles(user, true);
            return roles.OfType<RoleInfo>().ToList();
        }
```

Adding a filter based on expiry date as below resolves the issue:

```c#
private List<RoleInfo> GetCustomerRoles(CustomerAccount customer)
        {
            var user = DnnUserController.Instance.GetUser(_portalId, Convert.ToInt32(customer.Bvin));
            var roles = RoleController.Instance.GetUserRoles(user, true);
            // filter roles to those that are not expired
            var activeroles = from role in roles
                              where role.ExpiryDate != DateTime.MinValue 
                                    && role.ExpiryDate > DateTime.Now
                              select role;
            return activeroles.OfType<RoleInfo>().ToList();
        }
```

The question is whether this is the correct way to resolve the issue, or whether the fix should be applied elsewhere?

**Comment by hismightiness** [comment]
Have you already tried applying the fix you outlined?  If you have what testing have you done to verify it?  I haven't dug into this in great detail myself yet, but so far, this looks right.

**Comment by parasdaryanani** [comment]
Yes I tried this but had to modify the LINQ query as it filtered out roles that do not expire because of `role.ExpiryDate != DateTime.MinValue`.

Changed this as follows:
```c#
private List<RoleInfo> GetCustomerRoles(CustomerAccount customer)
        {
            var user = DnnUserController.Instance.GetUser(_portalId, Convert.ToInt32(customer.Bvin));
            var roles = RoleController.Instance.GetUserRoles(user, true);
            // filter roles to those that are not expired
            var activeroles = from role in roles
                              where role.ExpiryDate == DateTime.MinValue // permanent roles
                                    || role.ExpiryDate > DateTime.Now // active roles
                              select role;
            return activeroles.OfType<RoleInfo>().ToList();
        }
```
I used the above "steps to reproduce" to manually test for expected results with VS debugging. This works as expected.

Any suggestions on what to do next?

**Comment by hismightiness** [comment]
Please create a pull request so someone can debug it.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
