### ISSUE TITLE
Edit Shipping Zone: Easteregg or awesome bug?

### ISSUE THREAD

**Issue by Navilois** [HotcakesCommerce/hotcakes-commerce-core#217]
## Describe the bug
When editing a shipping zone and selecting South Korea at the country dropdown, it immediately changes the selected country to North Korea. Effectively, it is impossible to add South Korea to a shipping zone. 😂

## Software Versions
- DNN:  09.03.02
- Hotcakes:  03.02.00

## To Reproduce
1. Go to Hotcakes Admin -> Shipping Zones -> Add or Edit a shipping zone
2. Click on the country dropdown below 'Areas in this Zone'
3. Select South Korea

## Expected behavior
South Korea should be selected.

## Actual behavior
North Korea is selected.

## Additional context
I have to ask. Was Kim Jong-un involved in the development of Hotcakes? 👥

**Comment by hismightiness** [comment]
LMAO!!!  Wow... I first noticed this a very long time ago when I first took over Hotcakes Commerce back when it was still commercial.  I can't believe it's back!  🤦‍♂
