### ISSUE TITLE
Remove Telerik Dependencies & Replace w/ Alternative

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#226]
Telerik is no longer a built-in feature in new installations of DNN.  It needs to be removed from Hotcakes Commerce and replaced with an open source alternative.

Upon upgrade, the telerik components that are specific to Hotcakes Commerce should be removed and replaced.  

Upon installation, the alternative should be used and there should not be any signatures leftover that refer to telerik.

**Comment by hismightiness** [comment]
Actively working on this right now for DNN 09.06+ compatibility.

**Comment by Navilois** [comment]
Ah very good to see - just upgraded to DNN 09.06.01 and I'm running into Telerik dependency issues.

**Comment by hismightiness** [comment]
Thanks @Navilois . We still have a few more issues to close out, including a couple that aren't here in GitHub yet, but we're aiming on getting this release out there ASAP.

**Comment by brewadmin** [comment]
Hi Will on one of my instances of Hotcakes on DNN 9.4.4, the drop downs to select views are not available, in fact none of the drop downs work in the HotcakesStore/Category-Viewer module settings. xcillion skin makes no difference

http://vividair.itm.co.za/Portals/12/Drop-downs-not-working.png?ver=2020-05-25-102652-653

**Comment by hismightiness** [comment]
@brewadmin please see the rest of this issue. This is already known and resolved in a linked PR #251. We're just finalizing some remaining updates at this point in time. The milestone is otherwise completed.

**Comment by brewadmin** [comment]
Thanks Will

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za/> www.itm.co.za

**Comment by hismightiness** [comment]
So far, testing has been almost completely uneventful in DNN 9.6.1!  🙌 
![image](https://user-images.githubusercontent.com/938023/83072651-03214400-a024-11ea-95b2-bce2007e0e74.png)

**Comment by david-poindexter** [comment]
That's great news @hismightiness 🙌

**Comment by hismightiness** [comment]
I'm working on packaging today, but the release may not be ready until Monday or Tuesday at the earliest.  Final packaging and testing takes at least 8 hours for every release.  :)

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
