### ISSUE TITLE
Token [[LineItem.ProductDescription]] does not populate

### ISSUE THREAD

**Issue by teambound** [HotcakesCommerce/hotcakes-commerce-core#233]
The token [[LineItem.ProductDescription]] does not populate in the Gift Card Notification email. 

dnn 9.3
hotcakes 3.2.2

**Comment by hismightiness** [comment]
Are you using this token in the RepeatingSection or somewhere else?

https://hotcakescommerce.zendesk.com/hc/en-us/articles/210216623-E-Mail-Template-Tokens
