### ISSUE TITLE
SI:  E-Mail Address Shouldn't Be Case-Sensitive

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#239]
## Describe the bug
When checking out, if an e-mail address has any upper-case characters, it will likely result in the checkout reporting an invalid e-mail address/format.  

Support Request:  5378

## Software Versions
- DNN:  09.01.01
- Hotcakes:  03.02.03

## To Reproduce
1. Clean install of HCC 03.02.03 on any version of DNN.
2. Create at least one product.
3. As a "customer," add a product to the cart and then proceed to the checkout.
4. Checkout as a guest.
5. Fill in the e-mail address using an upper-case character, such as JaneDough@example.com
6. Fill in the rest of the checkout fields using known-to-be-valid values.  
7. Checkout.

## Expected behavior
Checkout should complete successfully without errors, and you should see the order receipt view.  

## Actual behavior
Checkout displays an error message stating that the e-mail address format is invalid.  

## Proposed Solution  
The e-mail address should just be set to all lower-case to prevent any issues.  However, the validation process should still accept the upper-case version, just in case.

**Comment by hismightiness** [comment]
In the viewset, changing the `IsEmailKnown()` method in Checkout.js resolves this client-side.

```js
    function IsEmailKnown(forceSwitch, emailfieldid) {
        if ($(emailfieldid) && $(emailfieldid).val() != undefined) {
            $(emailfieldid).val($(emailfieldid).val().toLowerCase());
        }
        if ($('#customeremail') && $('#customeremail').val() != undefined) {
            $('#customeremail').val($('#customeremail').val().toLowerCase());
        }
        var emailfield = $(emailfieldid || '#customeremail').val();
```

There still needs to be a fix applied server-side, presumably in the `CheckoutController` class.  However, the email validation routine itself needs to be reviewed, as it may not be address case sensitivity either way.

**Comment by puresystems** [comment]
Hi Will, we are now experiencing problems with this preventing customers from checking out and then abandoning the process which is upsetting the client. Is there any timescale on the server-side fix as the above client-side doesn't resolve the problem for us?

Thanks
Dan

**Comment by hismightiness** [comment]
@puresystems There is never a timeline that you can give a client when it comes to any open-source client (unless you're working on it yourself, or it's a sponsored update).  I hope you understand.  However, I am literally working on this right now.
