### ISSUE TITLE
Unable to set zero price when "Allow User Supplied Price" option selected

### ISSUE THREAD

**Issue by sumanbanda** [HotcakesCommerce/hotcakes-commerce-core#240]
## Describe the bug
Even after selecting "Allow 0 Dollar Orders" in order settings, the application not allowing to set the price to zero for a product when "Allow User Supplied Price" option selected. But when i unchecked "Allow User Supplied Price", it works well.

## Software Versions
- DNN:  08.00.04
- Hotcakes:  3.2.0

## To Reproduce
1. Go to 'Products' which i set "Allow User Supplied Price" in product settings.
2. Click on 'Add to Cart'
4. See error "Price contains invalid value.", Failed to add product to cart

## Expected behavior
Need to allow zero price for the product for "Allow User Supplied Price"

## Actual behavior
It is not allowing the product to add to the cart.

## Screenshots

![Hotcakes_Error2](https://user-images.githubusercontent.com/40234778/74938535-309e9600-5414-11ea-8996-456684e75e19.jpg)

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

## Additional context
Please reply as soon as possible for this issue.

**Comment by hismightiness** [comment]
This is by design.  The User Supplied Price functionality was originally only intended to be used for Donation-style products.  Changing this functionality in the core of Hotcakes Commerce could create unintended consequences for stores that use the donation feature.  You don't want to discount donations.
