### ISSUE TITLE
Posting to REST API to Update Order does not properly read the InputStream from the Request

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/hotcakes-commerce-core#243]
## Describe the bug
When posting to the REST API to update an order the ApiRestController is not reading the posted data from the InputStream. The posted data always comes out as string.empty.

## Software Versions
- Hotcakes:  03.02.03

## To Reproduce
1.  Post a OrderDTO to the OrderUpdate REST endpoint. Something similar to this:

```
            using (var content = new StringContent(JsonConvert.SerializeObject(data), System.Text.Encoding.UTF8, "application/json"))
            {
                var httpClient = m_HttpFactory.CreateClient("HotcakesQueryProcessor");
                return await httpClient.PostAsync(endpoint, content);
            }
```

2. When the APIRestController goes to read the ```Request.InputStream``` the posted data will always come out as an empty string.

## Expected behavior
When reading from the ```Request.InputStream``` the posted data should be what was posted.

## Actual behavior
The posted data is always read as an empty string.

## Additional context
I am posting the data from a netcore app. Since Hotcakes REST Api is not compatible with netcore I had to call the endpoint manually, instead of using the built in library functions.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
