### ISSUE TITLE
Customer IP Address on Authorize.NET is Always 0.0.0.0

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/hotcakes-commerce-core#249]
## Describe the bug
When using Authorize.NET as the Payment Gateway for Credit Card payments you can record the customer's IP address in the transaction. However, every credit card payment made through Authorize.NET shows 0.0.0.0 as the Customer IP Address.

## Software Versions
- DNN:  9+
- Hotcakes:  03.02.03

## To Reproduce
1. Make sure Authoirze.NET is set as your payment gateway
2. Add an item to your cart
3. Click on Checkout
4. Fill in the Checkout page and payment details
5. After a successful order is placed go to Authorize.NET and view the transaction details. See that the Customer IP Address is 0.0.0.0.

## Expected behavior
The customer's IP Address should be set in the Customer IP Address field in the Authorize.NET Transaction.

## Actual behavior
The Authorize.NET transaction shows 0.0.0.0 as the Customer IP Address.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
