### ISSUE TITLE
SI: Viewset Affiliate & Category (drilldown) views don't work

### ISSUE THREAD

**Issue by WillStrohl** [HotcakesCommerce/hotcakes-commerce-core#292]
## Describe the bug
When any of the following views are used with the Mandeeps Porto5 viewset, they don't work and instead throw JS exceptions.

## Software Versions
- DNN:  09.06.01
- Hotcakes:  03.04.00

## To Reproduce
1. Install DNN 
2. Install the Porto 5.x theme
3. Install Hotcakes
4. Add sample products and categories
5. Enable the affiliate program.
6. Add a new page that's visible to everyone.
7. Add the Affiliate Registration module to this new page.
8. Add a new page that's visible to at least Registered Users.
9. Add the Affiliate Dashboard module to this new page.  
10. In a new browser or incognito window, attempt to register as a new affiliate, filling in all fields except for the Referral Affiliate ID.  

Steps to Reproduce the Behavior:
1. Follow steps 1 through 4 above.  
2. In any instance of the category viewer module, configure it to use the drilldown view in module settings.

## Expected behavior
The drilldown and affiliate views work without reporting JS exceptions.  

## Actual behavior
There are JS exceptions thrown in the developer console.

**Comment by hismightiness** [comment]
As reported in support ticket # 5740, this is not limited to the Porto viewset.
