### ISSUE TITLE
CI: Cant Create/Update address in AddressBook

### ISSUE THREAD

**Issue by AnonDevelopment** [HotcakesCommerce/hotcakes-commerce-core#30]
If you try an update/create a new address on 3.0 it posts back but does not do anything with min required info.
/HotcakesStore/Address-Book

I have attempted to look for an outlier and led to perhaps address verification, but didnt dig in too much.

**Comment by hismightiness** [comment]
This is confirmed to be a bug in Hotcakes 03.00.01

**Comment by hismightiness** [comment]
https://hotcakes.org/Forums/g/posts/m/605/Issue-Update-addresses-in-AddressBook

**Comment by hismightiness** [comment]
https://hotcakes.org/Forums/g/posts/m/866/Error-on-Edit-Addresses-in-Adress-Book

**Comment by hismightiness** [comment]
Confirmed to be resolved in the pending 03.02.02 release.
