### ISSUE TITLE
Allow add to cart with decimal value

### ISSUE THREAD

**Issue by rashidbilgrami** [HotcakesCommerce/hotcakes-commerce-core#301]
While trying to add 1/2 KG to cart, it's giving an error because 0.5 value is not acceptable in add to cart. Please allow this feature to fulfils the feature who are selling general good items like vegetables, fruits and other groceries stuff

**Comment by hismightiness** [comment]
Thank you for creating an issue here.  :) 

We don't think that changing the quantity to a decimal value is an update that would be good for the platform.  There are just too many cascading issues that could impact all areas of the solution.  Instead, it would be better to indicate in the product details that each 0.5kg of the product is a quantity of 1 when ordering.  

This is mentioned in the community forums as well.  

https://mmmcommerce.com/Forums/g/posts/m/1449/Qty-in-add-to-cart-with-decimal-value
