### ISSUE TITLE
How to assign pricing group in bulk/mass to hundreds of users at once?

### ISSUE THREAD

**Issue by tarottapioca** [HotcakesCommerce/hotcakes-commerce-core#321]
Could someone help me by providing either the SQL query to use or point me at another way of being able to assign hundreds of users at once/quickly to a particular Price Group in hotcakes?  I do see that the pertinent field for this in User Profile is HccPricingGroupId. and in my testing I can see the GUID value for the price group that would need to be put into that HccPrcingGroupId field.  I would like to not have to do this one by one for several hundreds of users.

By the way I am also seeing a bug where I am not able to go in to an existing Customer in Hotcakes Administration and edit the user.  Any change I attempt to make for an existing user, including changing Price Group assignment, does not get saved.  I'm able to access the User Profile in DNN's user management though in order to perform necessary changes.

**Comment by hismightiness** [comment]
Questions like this would be best asked in our Forums.  We try to limit GitHub Issues to bugs and enhancements.  Do you think you can ask this question there?  I hope you don't mind.  :)  

https://mmmcommerce.com/forums
