### ISSUE TITLE
HCC core, DNN9.1.1 and Skins

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/hotcakes-commerce-core#33]
When using HCC 3.0 in DNN9.1.1 I'am getting the following error:
	-	Unhandled error loading page.
	-	The file '/Portals/_default/Skins/Gravity/2-Col.ascx' does not exist.

Solution to this is to remove <skinsrc>[G]Skins/Gravity/2-Col.ascx</skinsrc> from the (template) code.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
