### ISSUE TITLE
Product Viewer does not display product details without "slug" in url

### ISSUE THREAD

**Issue by puresystems** [HotcakesCommerce/hotcakes-commerce-core#340]
## Describe the bug
Product Viewer does not display product details without "slug" in url. i.e.

www.mysite.com/store/product-viewer/product1
This url does not display the product

www.mysite.com/store/product-viewer/slug/product1
This url does display the product

The urls generated by the Category Viewer don't include slug and this is what we'd expect.

## Software Versions
- DNN:  09.06.00
- Hotcakes:  03.05.00

## To Reproduce
1. On Dnn site, add Culture - English (United Kingdom) and make default and disable English (United States)
2. Install fresh version of HC 3.5.0 and run through setup wizard using defaults and let it create the relevant pages.
3. Add product category and product
4. View the Category Viewer page and click on the product
5. Product viewer page is blank

## Expected behavior
Product Viewer page should display the product using the urls from the Category Viewer page

## Actual behavior
Product Viewer page does not show product details.

**Comment by hismightiness** [comment]
Can you confirm your URL provider setting from your web.config?  It might look like the example below.  

```xml  
<friendlyUrl defaultProvider="DNNFriendlyUrl">
  <providers>
    <clear />
    <add name="DNNFriendlyUrl" type="DotNetNuke.Services.Url.FriendlyUrl.DNNFriendlyUrlProvider, DotNetNuke.HttpModules" includePageName="true" regexMatch="[^a-zA-Z0-9 _-]" urlFormat="advanced" />
  </providers>
</friendlyUrl>
```  

Also, what settings do you see in place in the persona bar for URL providers?  Settings > SEO > Extension URL Providers

**Comment by puresystems** [comment]
Hi Will,

The url provider DNNFriendlyUrl is as you've posted,n and i've attached a screenshot of the URL providers below.

![seo-settings](https://user-images.githubusercontent.com/4923523/102394572-db022e00-3fd1-11eb-9e3c-dbccff5784d8.jpg)

**Comment by moslem7026** [comment]
this problem occure when just one culture is enabled in dnn and that culture is not en-us. so dnn Urlprovider Culture Code Is Empty
this problem can be solved in url Extension Provider and set portal default culture if above statement is true
