### ISSUE TITLE
Remove Control Panel

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#36]
The control panel UX is different between CMS versions 8.x and 9.x.  This presents a large number of challenges with Hotcakes experience by end users.  The control panel includes a product/category performance chart and a direct edit link, with the vision to do more with it later.

This issue proposes removing the control panel entirely from the e-commerce core, and moving the new features to the header area of the product and category views, respectively.  

The control panel may be used by sites remaining on CMS 8.x, so switching it could present a usability challenge and/or crash the site.  Therefore, removing it includes:

- getting rid of the code and related files (including cleanup upon upgrade)
- updating the solution/project files.
- INSTALL:  updating the MSBuild/web deploy packages
- UPGRADE: SQL update to look for the CMS "core" control panel and switching to that upon upgrade
- INSTALL/UPGRADE: detect version 9.xx of the CMS and add an ecommerce link to the persona bar
- UPGRADE: double-check for admin/host menu dashboard links and add them if they're missing

**Comment by moslem7026** [comment]
for better contribution  , Please Release V 3.0.1 and DNN 9.1 Capability to grow HCC community  , and other users and developers join to HCC too.

**Comment by kurtwilbies** [comment]
Next week I will clone the project start adding pull request to make hcc 3 dnn 9.1 ready. Is it an idea to create another branche called hcc3.1 or something that shows that the latest dnn is the target.
