### ISSUE TITLE
SI: Upgrade/Replace plupload

### ISSUE THREAD

**Issue by WillStrohl** [HotcakesCommerce/hotcakes-commerce-core#361]
## Is your feature request related to a problem?
The plupload plugin is outdated and either needs to be replaced or upgraded.  

## Describe the solution you'd like
Most ideal, it would be nice to simply upgrade this plugin to have the least amount of impact across the solution.  

## Describe alternatives you've considered
None yet, but replacing this plugin could be an option as well.  

## Additional context  
- Internal Support Request Number:  7229

**Comment by erw13n** [comment]
The plugin is being archive (https://github.com/blueimp/jQuery-File-Upload)
It's better to replace it with something else, such as:
- [bootstrap-fileinput](https://github.com/kartik-v/bootstrap-fileinput)
- [filepond](https://github.com/pqina/filepond)
- [dropzonejs](https://www.dropzone.dev/js/)

**Comment by WillStrohl** [comment]
> The plugin is being archive (https://github.com/blueimp/jQuery-File-Upload) It's better to replace it with something else, such as:
> 
> * [bootstrap-fileinput](https://github.com/kartik-v/bootstrap-fileinput)
> * [filepond](https://github.com/pqina/filepond)
> * [dropzonejs](https://www.dropzone.dev/js/)

That's great and definitely should be looked into for a future update, but it's not directly related to this task.  What's left to be done on this one?
