### ISSUE TITLE
CI: UPS Online Tools Registration is broken

### ISSUE THREAD

**Issue by joshgk00** [HotcakesCommerce/hotcakes-commerce-core#363]
## Describe the bug
Registering for the UPS Online Tools to setup shipping rates appears to be broken. Hotcakes is having trouble parsing the XML response. This also has a knock-on effect when trying to retrieve rates for UPS on an existing site. It looks like something has changed with the UPS API endpoint which is causing the integration to break. 

## Software Versions
- DNN:  09.08.01
- Hotcakes:  03.05.00

## To Reproduce
1. Go to Hotcakes Administration > Admin > Shipping Methods
2. Click on Add Shipping Method
3. Select UPS
4. Click the link 'Register with UPS to use their online tools'
5. You'll see the error
   
    ![image](https://user-images.githubusercontent.com/13650025/123097738-6a175500-d3fe-11eb-8c46-d1e492476126.png)

## Expected behavior
When clicking on the Registration link, you should be able to register for the UPS Online Tools

## Actual behavior
An error message is displayed that Hotcakes isn't able to parse the response received from the UPS endpoint

## Error log
No error is logged

**Comment by WillStrohl** [comment]
We're able to duplicate this on DNN 9.9.0 and Hotcakes Commerce 3.6.0.  

![image](https://user-images.githubusercontent.com/938023/149196452-f1e1d1ec-db9e-4186-85ca-6637d333094c.png)

Also, this is reported in the community forums:  https://mmmcommerce.com/Forums/g/Posts/m/1689/UPS-OnLine-Tools-License-Application-Error
