### ISSUE TITLE
Problem with Require Phone Number Validation Text

### ISSUE THREAD

**Issue by moorecreative** [HotcakesCommerce/hotcakes-commerce-core#366]
## Describe the bug
This is a continuation of an earlier feature request... it may have a bug or issue?
https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/41
My question about this is to ask if this was fully impimented or only started?

In the latest version of HotCakes 3.5, we have the checkbox present in the admin interface, BUT, within the checkout page of teh site, if the phone is not completed, a validation message displays but is blank! You can see it in the screenshot below.

![image](https://user-images.githubusercontent.com/5497943/125125028-07dd7600-e0c7-11eb-8264-5995b0d6aa76.png)

Within the Languages file (Local > Desktopmodules > Hotcakes > Core > Admin > Controls > App_LocalResources > AddressEditor.ascx) where the records are which Hotcakes Uses, we found a phone message text that says "Phone Number Is Required". So it looks like it's there and ready to use, but we're seeing it not display that message within the checkout page.

![image](https://user-images.githubusercontent.com/5497943/125140205-fbb1e280-e0df-11eb-8f76-cd9e5b6ea27e.png)

## Software Versions
- Hotcakes:  03.05.00

## To Reproduce
1. In the Hotcakes Admin screens, under Orders set the checkbox to checked to enforce Phone required at checkout.
2. In an incognito session, add an item to cart and go to checkout 
3. complete all of the fields except for the phone field and submit
4. This will display the validation message that phone is required, and the text is not present, though the red styled div is visible.

## Expected behavior
Show the text message in validation

## Actual behavior
We need to check on why the text message is not displaying, it is not present in the rendered code. it is present in the language file

**Comment by hismightiness** [comment]
This sounds like you haven't merged your viewset when you upgraded Hotcakes Commerce.  

https://hotcakescommerce.zendesk.com/hc/en-us/articles/209637973-What-to-do-When-Upgrading-Hotcakes  

If this isn't the case and you find another cause, please feel free to reopen this issue.
