### ISSUE TITLE
SI: User Supplied Price Minimum Quantity Error

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#372]
## Describe the bug  
When using the user-supplied price feature, you're unable to add the product to the cart without entering a quantity.  

## Software Versions
- DNN:  09.10.01
- Hotcakes:  03.05.00

## To Reproduce
1. Clean install and complete the getting started wizard.  
2. Add at least one product that's using the user-supplied price (for donation-style products).  
3. Check the "Hide Quantity" checkbox.  
4. Save the changes.  
5. Navigate to the product in the store.  
6. Enter any donation amount.  
7. Click to add the donation to the cart.  

## Expected behavior
The donation product is added to the cart with a quantity of 1, and you're redirected to the cart view with the expected amount.  

## Actual behavior
The view stays on the product and displays an error about there not being a number in the quantity field (see screenshot).  The error message states, "Please enter number only in quantity."  

## Screenshots  
![image](https://user-images.githubusercontent.com/938023/133349142-b0b721c2-f744-47be-9c01-30b09e196176.png)

## Additional Context  
Customer support request 7671

**Comment by erw13n** [comment]
@hismightiness Error happen because Quantity is Null
