### ISSUE TITLE
Exception occurs when editing a Product Type Property that is associated with a product.

### ISSUE THREAD

**Issue by jcmrva** [HotcakesCommerce/hotcakes-commerce-core#378]
```
[NullReferenceException: Object reference not set to an instance of an object.]
   Hotcakes.Modules.Core.Admin.Catalog.ProductTypePropertiesEdit.get_ProductPropertyChoiceId() +52
   Hotcakes.Modules.Core.Admin.Catalog.ProductTypePropertiesEdit.<btnUpdateChoice_Click>b__8(ProductPropertyChoice y) +13
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +173
   Hotcakes.Modules.Core.Admin.Catalog.ProductTypePropertiesEdit.btnUpdateChoice_Click(Object sender, EventArgs e) +223
   System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) +136
   System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) +147
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5027
```

## Software Versions
- DNN:  09.09.01
- Hotcakes:  03.05.00

## To Reproduce
1. Go to Edit Product Type Property
2. Edit an option (choice name & display name) that that has been set on a product
3. Click Update

![image](https://user-images.githubusercontent.com/20140997/143064036-c4a7e196-8dce-4ca7-9831-03ea80d76fa9.png)

I was able to edit a similar newly added option without error. Also, other choices were editable. Possibly an issue with that specific name or removing the hyphen?

## Workaround
Update via SQL directly in `hcc_ProductPropertyChoiceTranslations` and `hcc_ProductPropertyChoice`

**Comment by WillStrohl** [comment]
Are these the specific options that cause this error, or are those option names different?

**Comment by jcmrva** [comment]
The option in the screenshot is the one we tried to edit.

**Comment by erw13n** [comment]
Issue confirmed, able to reproduce it.
Happen when editing `multiple choice` type properties.
