### ISSUE TITLE
Checkout CleanCreditCard error after 3.6.0 upgrade

### ISSUE THREAD

**Issue by puresystems** [HotcakesCommerce/hotcakes-commerce-core#385]
## Describe the bug
Using Credit card checkout, on submitting the payment form, the form says the payment failed and asks for it to be entered again, in the DNN log we see an error.

## Software Versions
- DNN:  9.3.2
- Hotcakes:  3.6.0

## To Reproduce
1. Add a product to the basked and go to checkout
2. Select Credit Card payment and enter details
3. Click Pay Now to complete purchase

## Expected behavior
Payment is processed

## Actual behavior
The payment displays the standard Payment Failed message and ask the user to retry.

## Error log
AbsoluteURL:/DesktopModules/Hotcakes/API/mvc/checkout/CleanCreditCard
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:31024cdc-1c1b-4bba-aa4a-1632ce5aa085
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:WHIS170eMrXhMvqDJ9fo2XqaVHk=
Message:Length of the data to decrypt is invalid.
StackTrace:
at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) at System.Security.Cryptography.CryptoStream.FlushFinalBlock() at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing) at System.IO.Stream.Close() at System.IO.StreamReader.Dispose(Boolean disposing) at System.IO.TextReader.Dispose() at Hotcakes.Modules.Core.Controllers.CheckoutController.DecryptStringFromBytes(Byte[] cipherText, Byte[] key, Byte[] iv)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

## Additional context
We had upgraded HC from 3.2.3 to 3.6.0, previously it was working. I wonder if there is something out of date which we've missed when upgrading which has broken something.

**Comment by WillStrohl** [comment]
We didn't see this during testing.  Which payment method(s) are you seeing this with?

**Comment by puresystems** [comment]
So the Payment Method is set to Credit Card.

Credit Card options:
- Accepted cards = Visa, MasterCard
- Capture Mode = Charge Full Amount at Checkout
- Gateway is a custom direct integration
- Require CVV = true

I'm sure that this would have been spotted by now which makes me wonder if something (dll) is out of date possibly.

**Comment by mtrutledge** [comment]
Check your Hotcakes View. The Checkout.js Script was updated to encrypt the credit card number in transit. If you have customized your view set you will need to update your views. I was seeing this same error because my Checkout.js in my custom view set was not updated. Start at this line: https://github.com/HotcakesCommerce/hotcakes-commerce-core/blob/d99611e477e2e2d0f82df99e1e65678504c162fb/Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js#L19

**Comment by puresystems** [comment]
Thanks! Missed the js updates from the HC View, that solved the problem.

**Comment by mtrutledge** [comment]
@puresystems Awesome. Glad to hear that worked. Can you close this issue? Or is that something @WillStrohl will have to do?
