### ISSUE TITLE
Could not load type 'Hotcakes.Modules.Core.Admin.Parts.CreditCardGateways.Shift4.Edit'.

### ISSUE THREAD

**Issue by BhawanaPokhariya** [HotcakesCommerce/hotcakes-commerce-core#40]
\DesktopModules\Hotcakes\Core\Admin\Parts\CreditCardGateways\Shift4\Edit.ascx  is not found in hotcakes 3.0.0 version .
Hotcakes extension is added to DNN_Platform_8.0.4.226 version.

**Comment by hismightiness** [comment]
Can you please describe how you generated this error/issue?

**Comment by hismightiness** [comment]
Resolved in PR #180
