### ISSUE TITLE
SI: Option to make the billing phone number in checkout required

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#41]
As a store owner, I would like to be able to enforce the billing phone number to be required during checkout, so that I may be able to call customers to resolve any payment and order issues.

As a designer/developer, I would like to be able to enforce the billing phone number to be required during checkout as a configuration option, so that I don't have to write any code to make the phone number required.

This update will add a new configuration option in the Admin > Orders view as a checkbox to allow a store owner to require the billing phone number during checkout.  New installations will have this setting enabled by default.  Upgraded installations will not require the phone number, to preserve existing functionality on stores that are already launched.

If upgraded stores were automatically updated to have the clean-install behavior, it could create unintended consequences, especially for any store that may have created their own solution to require the phone number.

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone

**Comment by moorecreative** [comment]
My question about this is to ask if this was fully impimented or only started?

In the latest version of HotCakes 3.5, we have the checkbox present in the admin interface, BUT, within the checkout page of teh site, if the phone is not completed, a validation message displays but is blank! You can see it in the screenshot below.

![image](https://user-images.githubusercontent.com/5497943/125124556-47579280-e0c6-11eb-8113-48cf2571c97e.png)

Within the AddressEditor.ascx.portal.0.resx where the language records are which Hotcakes Uses, we found a phone message text that says "Phone Number Is Required". So it looks like it's there and ready to use, but we're seeing it not display that message within the checkout page.
