### ISSUE TITLE
Module Load Exception - Module load exception with all Hotcakes modules

### ISSUE THREAD

**Issue by Manfred-Hain** [HotcakesCommerce/hotcakes-commerce-core#411]
## Please summarize your question in one sentence
After installing HCC, all the modules have Module load exceptions.

## Give a more extended description
The error that I get for the Category Viewer module is pasted below, but it seems to be the same for all HCC modules. The ViewSet used is the default viewset.

Error: Category Viewer is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Execution of the child request failed. Please examine the InnerException for more information. ---> System.Web.HttpException: Execution of the child request failed. Please examine the InnerException for more information. ---> System.Web.HttpException: The controller for path '/Default.aspx' was not found or does not implement IController. at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func) --- End of inner exception stack trace --- at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func) at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage) at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm) at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter) at System.Web.Mvc.Html.ChildActionExtensions.Action(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues) at Hotcakes.Commerce.Dnn.Mvc.MvcRenderingEngine.Render(String controllerName, String actionName, String viewName, Object routeValues) at Hotcakes.Modules.CategoryViewer.CategoryViewerView.RenderView() at Hotcakes.Commerce.Dnn.Web.HotcakesModuleBase.OnLoad(EventArgs e) --- End of inner exception stack trace ---

## Steps to reproduce (if needed)

The only step taken was to install HCC.

## Other comments or remarks

The version of DNN is 9.8.1 and has been upgraded over time from 7.x.x  and the version of HCC installed is 3.6.0. I think this could be more to do with the DNN. Completely stumped.
![Capture1](https://user-images.githubusercontent.com/5827066/191685984-eb75a8e2-926f-407a-98e6-b81e1c75f5b8.JPG)

**Comment by WillStrohl** [comment]
Unfortunately, this must be something environmental.  I just tried installing and using Hotcakes Commerce 3.6.0 and DNN Platform 09.08.01.  I experienced no issues.  Here's a video showing it.  I don't know how long the internet will keep it live, but it's here for you now.  :) 

https://www.screencast.com/t/9RaiLrO5FN
