### ISSUE TITLE
Currency decimal value remove

### ISSUE THREAD

**Issue by uzmannazari** [HotcakesCommerce/hotcakes-commerce-core#415]
Hi @WillStrohl

Rial currency unit does not have a decimal value in Iran.
But in Hotcake, it has a decimal value.
How can I remove the decimal value in HotCake from Rial currency?

**Comment by WillStrohl** [comment]
The currency formatting comes from .NET, not Hotcakes.  This has come up in the past, but I forgot what the actual "fix" was.  It was less to do with Hotcakes, though.  Maybe you can find it in an earlier issue here, or in the [Hotcakes community forums](https://mmmcommerce.com/forums).
