### ISSUE TITLE
fixed bug

### ISSUE THREAD

**Issue by kenixzulu** [HotcakesCommerce/hotcakes-commerce-core#424]
## Software Versions
- DNN:  00.00.00
- Hotcakes:  00.00.00

## To Reproduce
4. See %

## Actual behavior
A clear and concise description of what happened instead.

## Approved log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the successful with the debug DLL's before pasting the log.

Paste the successful log that is related to this issue.

**Comment by WillStrohl** [comment]
@kenixzulu What is this supposed to be related to?
