### ISSUE TITLE
+ Add Order unable to Find Customers

### ISSUE THREAD

**Issue by james7342** [HotcakesCommerce/hotcakes-commerce-core#451]
## Describe the bug
Dashboard/Order/ +Add Order. Unable to lookup customers. Using _default viewset with no customizations.

## Software Versions
- DNN:  9.11.2
- Hotcakes:  3.6.0

## To Reproduce
1. Dashboard/Orders
2. + Add Order
3. On the Add Order page Click the option to Find Customer, Provide a Keyword, and press "Find Customers"
4. Search for Customers will say "Found X Matching Customers"
5. Even though it found customers nothing is displayed. 

## Expected behavior
Able to find Customers as noted in documentation
https://hotcakescommerce.zendesk.com/hc/en-us/articles/210897423-Add-Order

## Actual behavior
No customers are displayed. 

## Screenshots
![screenshot_805](https://user-images.githubusercontent.com/27960723/231300676-8dcbece8-467e-43f8-b97d-d8b28da40226.png)

## Error log
**Note: Debug DLL's**
N/A

Paste the error log that is related to this issue.

## Additional context
N/A

**Comment by WillStrohl** [comment]
Thank you for reporting this issue.  We'll attempt to reproduce the issue and respond here once we're done.

**Comment by ismaelTartola** [comment]
@james7342 I was able to confirm the bug using the steps to reproduce posted in the issue description.

CC: @WillStrohl

**Comment by WillStrohl** [comment]
Hello @james7342 ...  This may or may not have been fixed since this issue was originally reported.  We are not able to reproduce this today.  Do you have a specific example of user details that you were searching for and didn't find?  This way, we can troubleshoot it again and find the root cause.

**Comment by james7342** [comment]
@WillStrohl, I can still produce it. Either I'm miss understanding what the expected results are supposed to be or it's not working properly. What I'm expecting is if I search for a member and there is more then 1 match it should return a list and let me select the customer. If I search and there is only 1 result it will auto select that user and start to populate the order details, IE: First, Last, Email etc. But in this case using my name returned 6 results but there is no list or details provided listing the 6 customers it found.

Tested on Safari 18.1.1 and Chrome 131.0.6778.109.

![screenshot_1955](https://github.com/user-attachments/assets/2d939db2-76e9-4590-aafc-3b3f0114c269)

**Comment by james7342** [comment]
Just reviewed the pull request and thank you for this enhancement. Seems like the original issue was user error, but this enhancement will make it much more intuitive.
