### ISSUE TITLE
DNN SMTP Mail Provider with SSL

### ISSUE THREAD

**Issue by james7342** [HotcakesCommerce/hotcakes-commerce-core#453]
## Describe the bug
Mail Server configured in DNN to use SSL. When HCC sends email results in an error, "Server does not support secure connections."

## Software Versions
- DNN:  9.11.2
- Hotcakes:  3.6.0
- 
## To Reproduce
1. DNN Servers/SMTP/Configure SMTP server settings and enable SSL support. 
2. In HCC Create an order or send HCC to send an email using various methods. Order Management, etc. 
3. Email will not be sent and error written to Log.

## Expected behavior
Email is sent and no error

## Actual behavior
Email not sent and Event Error

## Screenshots
<img width="937" alt="screenshot_813" src="https://user-images.githubusercontent.com/27960723/231912381-fbdbc3ab-6cab-4e2f-adf3-0b54ebf933cf.png">

## Error log
N/A

## Additional context
I suspect this is due a port issue. As turning of SSL in DNN SMTP Mail Settings resolves issue. System.net.mail provider maybe defaultng to port 25 and SSL on most servers requires port 587. On a side note I do have DNN configured to use MailKit though I don't think that's an issues as it appears HCC is using the System.net.mail provider. HCC should use SMTP port DNN is using to send mail. I believe HCC is trying to honor the SSL requirement but using the incorrect port to make the connection.

**Comment by WillStrohl** [comment]
I don't think this is a Hotcakes Commerce issue.  I believe if you include the port number in your DNN SMTP settings, you may resolve this issue.  Have you tried that yet?  (See the example in the image below.)  

![image](https://github.com/HotcakesCommerce/hotcakes-commerce-core/assets/938023/1aa590dd-fe27-4495-8fc7-f2d52458a82f)

**Comment by james7342** [comment]
I wasn't using the :587 port in the URL and only had SSL enabled toggle. Which was working fine for normal DNN emails and i was only getting this above alert for HCC emails. I would have to test with the :587 port in the URL to see if that resolves it. I guess I sort of assumed with SSL toggle it would us port 587 would be used. Maybe it's just doing SSL of port 25.

<img width="779" alt="screenshot_949" src="https://github.com/HotcakesCommerce/hotcakes-commerce-core/assets/27960723/2c4c9292-173c-42e3-99e6-2a2cf2edfcca">

**Comment by james7342** [comment]
I wasn't using the :587 port in the URL and only had SSL enabled toggle. Which was working fine for normal DNN emails and i was only getting this above alert for HCC emails. I would have to test with the :587 port in the URL to see if that resolves it. I guess I sort of assumed with SSL toggle it would us port 587 would be used. Maybe it's just doing SSL of port 25.

<img width="779" alt="screenshot_949" src="https://github.com/HotcakesCommerce/hotcakes-commerce-core/assets/27960723/f705db73-eb7d-4e07-b4a1-f92b446825b1">

**Comment by WillStrohl** [comment]
Putting in the port number is not always required.  It more so depends on how the communication from DNN is parsed by the respective SMTP relay provider you're attempting to connect to.  

For the most part, emails from DNN and Hotcakes Commerce should be using the same code.  Our email logic wraps the DNN API email endpoints.

**Comment by WillStrohl** [comment]
It's better to send anything securely, if you can.  Did the port number change work, or no?

**Comment by james7342** [comment]
Tested a couple things here today.
1. Adding just port 587 to the SMTP Server field works. DNN Test Email, site emails and HCC emails are successful and no errors in the logs. 
2. Adding port 587 and also toggling the "SMTP Enable SSL" generated the error for HCC emails. DNN Test Email and Sites emails are successful. 

![screenshot_955](https://github.com/HotcakesCommerce/hotcakes-commerce-core/assets/27960723/513a574e-ebd4-4249-9c87-3a66decc6173)

There is something with the DNN "SMTP Enable SSL" toggled on. When enabled the DNN "Test SMTP Settings" is successful along with other DNN site based emails. Which leads me to believe SMTP SSL is working. 

The only module throwing the error is HCC. @WillStrohl - Do you have it toggled on in your configuration along with port 587 configured?

I'll reach out to our hosting PowerDNN/Managed.com to see if their SMTP relay services support SMTP SSL. I'm not sure if DNN "SMTP Enables SSL" tries SSL and falls back to non secure. Which is why all my normal DNN site emails work with it toggled on. Maybe my SMTP server doesn't support SSL and HCC using its own SMTP provider is trying to force SSL.

Something is strange here just not sure if it's DNN, HCC or my SMTP Mail Relay.

**Comment by james7342** [comment]
I think I’ve got the answer here. PowerDNN/Managed.com SMTP relay service doesn’t have SSL enabled.

From my support case. “The relay does not have SSL enabled”

So this looks more like a DNN issue as the “Enable SMTP SSL” toggle doesn’t actually enforce SSL. Though HCC is when it sees this enabled in the DNN configuration. Which is exactly what the generated error message is indicating. 

I’ll work on getting a discussion/issue started over there.

**Comment by WillStrohl** [comment]
Ah, well they really should support SSL to protect the emails going through.  :(  

Anyhow, it sounds like this isn't an issue anymore.  

@ArielBlanco1990  Please stop triaging.  :)

**Comment by james7342** [comment]
@WillStrohl Thanks for help on this. Adding my discussion from the DNN.Platform project. 

https://github.com/dnnsoftware/Dnn.Platform/discussions/5753

**Comment by WillStrohl** [comment]
My pleasure  :)
