### ISSUE TITLE
Abandoned Cart Email throwing exception

### ISSUE THREAD

**Issue by james7342** [HotcakesCommerce/hotcakes-commerce-core#454]
## Describe the bug
Enabled Abandoned Cart Email in Admin/Orders. Now every hour when the Scheduler Job "Send Abandoned Cart Emails" runs an Hotcakes Exception is logged in the Event Log. This also seems to be impacting the sending of the Email as since enabling in testing I haven't received and messages even though reports shows abandoned carts for known users.

## Software Versions
- DNN:  09.11.2
- Hotcakes:  3.6.0

## To Reproduce
1. Admin/Orders Check "Send e-mail if cart was abandoned"
2. Wait for the Scheduled Job to Run or Edit the Job and select "Run Now"
3. Check DNN Admin Logs and notice error

## Expected behavior
No error is generated

## Actual behavior
Error generated and no emails sent. 

## Screenshots
![screenshot_815](https://user-images.githubusercontent.com/27960723/232549600-53b3e686-0b1a-4281-b48c-b14ee52b395c.png)

## Error log
**Note: Debug DLL's**
Noted in attached message with PBD files installed. 
"Hotcakes.Modules.Core.AbandonedCartEmailJob.SendAbandonedCartEmail(HccRequestContext context, Order order) in C:\Work\HCC-core\hcc-core\Website\DesktopModules\Hotcakes\Core\AbandonedCartEmailJob.cs:line 90"

## Additional context
N/A

**Comment by WillStrohl** [comment]
Thank you for reporting this.  We'll take a look at it as soon as we can.
