### ISSUE TITLE
MMMCommerce Website no longer works!

### ISSUE THREAD

**Issue by BGillham** [HotcakesCommerce/hotcakes-commerce-core#463]
## Please summarize your question in one sentence
I am trying to get started with Hotcakes

## Give a more extended description
There is no "Install" Extension with the Source code 3.07

## Steps to reproduce (if needed)
Need to know how to Install Hotdesk???

## Other comments or remarks
Really have tried many options but this is not a time for guesswork and need beginner information!

**Comment by WillStrohl** [comment]
We don't distribute the source code as a package.  GitHub already does this for us, so it's not something we spend time on.  Sorry.  :( 

Any "Installation" package is not meant to include any source code, if it can be left out.  Instead, you can go to the main website to find and download the installation package, which follows the naming convention below.  

The correct name of the installation package is something like the following format:

`HotcakesCommerce_03.07.00_Core_Install.zip`

If version 3.7.1 were to be released at some point, that package name would only change in version number, such as the following example:

`HotcakesCommerce_03.07.01_Core_Install.zip`

Just to further the example so any future readers can also benefit, if the version were to be increased to 3.8.0 or 4.0, those examples are below.

`HotcakesCommerce_03.08.00_Core_Install.zip`  
`HotcakesCommerce_04.00.00_Core_Install.zip`  

With that being said, there are indeed other zip packages that all have specific purposes, but the primary one for nearly all use cases is what we're mentioning here.

Additional Background
Core refers to the core module. This is a legacy naming convention from when we were also deploying a CMS version of the module that included the module and DNN pre-integrated as a single solution.

**Comment by WillStrohl** [comment]
Oh, also, the website was ungoing a major upgrade over the past two weeks.  Among the updates were migrating to/from new modules, upgrading modules, and upgrading DNN.  With the history of this website, the upgrade can sometimes take a while.  Our apologies for you getting caught up in that timing.
