### ISSUE TITLE
SI: UPS to end AccountNumber/AccessKey service, need new UPS API Shipping Method

### ISSUE THREAD

**Issue by moorecreative** [HotcakesCommerce/hotcakes-commerce-core#487]
## Describe the bug  
Within the current version of Hotcakes, the current UPS Shipping provider will continue to work through June 2024. After that the plan from UPS is to retire the Access Key method and require new API format credentials for accessing the shipping rate service.

If a new UPS shipping provider has not already been built for Hotcakes, then we will need one operating in the next few months.

## Additional context
https://www.ups.com/upsdeveloperkit

> **Announcements and API Updates**
> If you were sent here by a software provider to obtain an access key, please share the below with them as they will need to update their integration to OAuth auth-code grant type in order to continue to enable their services.
> 
> **By June 2023, UPS will no longer issue new API access keys.**
> 
> UPS has implemented an OAuth 2.0 security model for all APIs to enhance the overall security for our customers, reduce fraud and provide enhanced API capabilities. OAuth replaces access keys with a client ID and client secret for authentication. New OAuth credentials must be created on the [UPS Developer Portal](http://developer.ups.com/).
> 
> **Changes to API Authentication:**
> UPS has deprecated access key authentication in favor of an OAuth 2.0 security model for all APIs. 
> 
> **Beginning June 3, 2024, access keys will no longer be supported for authentication to any UPS APIs.** 
> 
> After this date, all integrations must utilize the OAuth 2.0 authentication model to continue to transact with UPS APIs. Please ensure your integration has migrated to OAuth 2.0 as soon as possible to prevent future service disruptions and view the [OAuth migration guide ](https://developer.ups.com/oauth-developer-guide?loc=en_US)for more details on the impacts to your API integration with UPS.  

## Software Versions  
- DNN:  ALL 
- Hotcakes:  ALL 3.8.1+   

## Sponsorship  
This need for the Hotcakes system will require redevelopment of the UPS shipping provider. I have the following interest in helping to [sponsor the effort via GitHub Sponsors](https://github.com/sponsors/UpendoVentures):    

- [ ] None, please continute to work for me for free :P  
- [X] Absolutely, I get value out of this!  
- [ ] Maybe later  
- [ ] I'm already a sponsor... Woot!

**Comment by WillStrohl** [comment]
Another generous customer sponsored this update.
