### ISSUE TITLE
Stripe payment error: Parameter ID cannot be null or whitespace.

### ISSUE THREAD

**Issue by alex-pommier** [HotcakesCommerce/hotcakes-commerce-core#496]
## Sponsorship  

If this request requires additional support (e.g., such as direct email/phone/meeting/development), I have the following interest in helping to [sponsor the effot via GitHub Sponsors](https://github.com/sponsors/UpendoVentures):    

- [ ] None, please continute to work for me for free :P  
- [X] Absolutely, I get value out of this!  
- [ ] Maybe later  
- [ ] I'm already a sponsor... Woot!  

## Please summarize your question in one sentence
Stripe payment issue - Unknown Payment Error: The resource ID cannot be null or whitespace. Parameter name: id

## Give a more extended description
Tested with both sandbox & production api keys. The transactions stack always shows the error below, also tried various cards both  test & live. Incremented the starting order # on HC backend.

DNN Version: 9.13.04
Hotcakes Version: 3.8.1

```$10.00 - Credit Card Charge
9/25/2024 5:27:13 AM
FAILED
MasterCard xxxx-xxxx-xxxx-4444
exp: 1/2028
Ref#: pi_3Q2rVuFoT6bPqMXu0PgRren5
:: HCP_SP_1001 - Unknown Payment Error: The resource ID cannot be null or whitespace. Parameter name: id :: STACKTRACE - Stack Trace at Stripe.Service`1.InstanceUrl(String id) in /_/src/Stripe.net/Services/_base/Service.cs:line 579 at Stripe.PaymentIntentService.Capture(String id, PaymentIntentCaptureOptions options, RequestOptions requestOptions) in /_/src/Stripe.net/Services/PaymentIntents/PaymentIntentService.cs:line 50 at Hotcakes.Payment.Gateways.StripeProcessor.CapturePaymentIntent(Transaction t) at Hotcakes.Payment.Gateways.StripeProcessor.ProcessTransaction(Transaction t)```

## Steps to reproduce (if needed)
Configure the Stripe payment gateway with publishable & secret keys. Run a test transaction. I can see the requests coming in on the stripe dashboard and they seem correct but Hotcakes always throws an error.

## Other comments or remarks  
- Different product amounts tested
- Checked the "not-shippable" in product details (Tested with & without)
- Checked the "not-taxable" in product details (Tested with & without)

**Comment by WillStrohl** [comment]
Hello @alex-pommier ...  Thank you for reporting this issue.  We had someone on our team attempt to reproduce the issue, but were not able to.  You should be able to also see this issue resolved in a more recent release of Hotcakes.

**Comment by WillStrohl** [comment]
Oh, and if you can still reproduce the issue, please provide more details to help our team also reproduce the issue.

**Comment by alex-pommier** [comment]
Thank you for reaching out. I am currently out of the office and will not be available until November 4th. 
I will respond to your email as soon as possible upon my return.

If your matter is urgent, please feel free to text me at 727-873-7371.

Thank you,
Alex Pommier
