### ISSUE TITLE
Make Mini Cart Module a SPA app

### ISSUE THREAD

**Issue by WillStrohl** [HotcakesCommerce/hotcakes-commerce-core#52]
The mini cart module functions using standard web forms functionality.  This should be rewritten to be more lightweight so it doesn't adverse affect page loads and site performance.

It should use AJAX/SPA patterns to reduce the page load.  

It should be better aware of the page that's being loaded so it doesn't perform the same logic twice (like when it's on the Cart page).

**Comment by mtrutledge** [comment]
Will,

Good to see you at DNN Summit. I will take a look at my code as I have about 80% of this done. The mini cart that I implemented uses a custom WebAPI endpoint that gets the items in cart and updates the view. I will have to add the individual line items in my view as well.

**Comment by mtrutledge** [comment]
Hey Will,

Maybe you can help me out. I am getting my dev environment set up according to the WIKI page and I can't seem to find a download of DNN Platform 8.00.03 from dnnsoftware.com. Do you know where I can download this? Could I download platform 9.1.1 and install and then follow the rest of the steps in the WIKI?

**Comment by hismightiness** [comment]
Here it is...  :)

https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v8.0.3

**Comment by mtrutledge** [comment]
Thanks Will!

**Comment by mtrutledge** [comment]
Pull request has been made.

**Comment by hismightiness** [comment]
Related to issue #53 (duplicate)

**Comment by hismightiness** [comment]
I moved this to another release because we need to sort out which Mini Cart SPA implementation should be included. Still waiting on Scott to reply to the other Issue.
