### ISSUE TITLE
TabIndex Order is Not Observed in Checkout

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/hotcakes-commerce-core#69]
When you go to the checkout page in Hotcakes 03.00.01 you can place your mouse/cursor focus in the first available field.  If you hit tab to proceed to the next field and so on, it will skip the billing address information and go to the bottom-most checkout fields.

**Comment by moslem7026** [comment]
it works correctly and all tab index is working properly, when `checkbox My billing address is the same as my shipping address` is Checked it jumps to in correctly. assume that first place is `Contry` DropDown List

**Comment by hismightiness** [comment]
We just finished cooking up a fresh batch of Hotcakes for you.  Enjoy!  ;)

https://dnncommunity.org/blogs/Post/5689/Hotcakes-Commerce-03-03-00-Release-Marks-a-Major-Milestone
