### ISSUE TITLE
SI: Users will not see the Menu in the Admin Area if they are not a Administrator

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/hotcakes-commerce-core#86]
In hotcakes 3.01 (we upgraded from 2.0.8) I have two users that are in a Product Manager Role and an Order Manager Role. When those users log in and go to the HCC Admin Area there is no menu across the top, only the hotcakes logo. If I add them to the Administrator Role the menu appears. It used to be they would only see the Catalog and Order menu.

**Comment by geo502** [comment]
Any updates on this, we are also running into this same bug and want to minimize the amount of users who should be administrators.  This issue prevents us from assigning specific roles to specific duties within the hotcakes role administration.

**Comment by hismightiness** [comment]
I've added the SI prefix to denote that one or more Hotcakes Commerce support clients are running into this issue.  This prioritizes the issue for our upcoming development cycle.

**Comment by hismightiness** [comment]
Resolved in PR #251
