### ISSUE TITLE
Improve Currency compability

### ISSUE THREAD

**Issue by moslem7026** [HotcakesCommerce/hotcakes-commerce-core#90]
currency for different culture inherit from .net framework.  and if store manager want to customize currency is not able to do . changing decimal point , and changing currency symbol or symbol position . 
for more user and worldwide distribution of Hcc it is good to be more customizable 
```
                    currencyCulture.NumberFormat.CurrencyDecimalDigits = 0;
                    currencyCulture.NumberFormat.CurrencySymbol = "تومان";
                    currencyCulture.NumberFormat.CurrencyPositivePattern = 3;
```
this configuration in admin panel can be applied .

**Comment by hismightiness** [comment]
There already is an ability to change how currency works.  See below...

https://hotcakescommerce.zendesk.com/hc/en-us/articles/208945486-Settings-Geo-Location

Could you please be more specific about what you're trying to accomplish?
